feat : 가계부 앱 서버 작성
hegunhee/ToyProjectServer pull request #6
Opened 2024-08-28 02:57 UTC by hegunhee

사용라이브러리, 프레임워크 버전
- Java : 17
- spring-boot : 3.3.2
- Spring Data JPA
- SLF4J
- lombok
- H2Database

2024-09-01 04:43 UTC, liquidjoo requested changes
PR 보내줘서 고마워
리뷰진행 후 몇 가지 코멘트 남겼어
확인하고 다시 알려줘

2024-09-01 04:43 UTC, liquidjoo commented on simplememo/simplememo/src/main/java/gunhee/simplememo/controller/CategoryController.java
> +    }
각 객체 만드는게 좋을듯

2024-09-01 04:43 UTC, liquidjoo commented on simplememo/simplememo/src/main/java/gunhee/simplememo/domain/memo/Memo.java
> +    @Id @GeneratedValue
@GeneratedValue
내부적으로 값이 있을텐데 디비에 따라 설정이 달라
해당 옵션들에 대해서 공부해보면 좋을듯
코멘트로 남겨줘 공부하고

2024-09-01 04:43 UTC, liquidjoo commented on simplememo/simplememo/src/main/java/gunhee/simplememo/domain/memo/Memo.java
> +    }
update 에 너무 많은 책임이 있는 것 같은데
나누어 보면 좋지 않을까 상황에 맞게

2024-09-01 04:43 UTC, liquidjoo commented on simplememo/simplememo/src/main/java/gunhee/simplememo/dto/TotalSum.java
> +    private final BigDecimal totalSum;
```suggestion
    @JsonFormat(shape = JsonFormat.Shape.STRING)
    private final BigDecimal incomeSum;
    
    @JsonFormat(shape = JsonFormat.Shape.STRING)
    private final BigDecimal expenseSum;
    
    @JsonFormat(shape = JsonFormat.Shape.STRING)
    private final BigDecimal totalSum;
```

가독성을 조금 더 신경써주면 좋을듯

2024-09-01 04:43 UTC, liquidjoo commented on simplememo/simplememo/src/main/java/gunhee/simplememo/dto/memo/MemosResponse.java
> +    }
Response가 DTO  인지 VO 인지에 따라서 달라질 것 같은데
DTO 라면 비즈니스 로직이 존재하는 것이 맞을까?

2024-09-01 04:43 UTC, liquidjoo commented on simplememo/simplememo/src/main/java/gunhee/simplememo/dto/memo/StaticsMemoDto.java
> +    private final BigDecimal price;
가독성 플리즈~

2024-09-01 04:43 UTC, liquidjoo commented on simplememo/simplememo/src/main/java/gunhee/simplememo/repository/MemoRepository.java
> +    @Query("select m from Memo m where YEAR(m.memoDate) = :year AND MONTH(m.memoDate) = :month ORDER BY DAY(m.memoDate) DESC")
쿼리 어노테이션 쓴 이유가 뭐야?

2024-09-01 04:43 UTC, liquidjoo commented on simplememo/simplememo/src/main/java/gunhee/simplememo/repository/MemoRepository.java
> +            "GROUP BY m.attribute")
쿼리 어노테이션을 썼을 때와 쓰지 않고 JPQL 로만 했을 때 어떤 차이가 있어?

2024-09-01 04:43 UTC, liquidjoo commented on simplememo/simplememo/src/main/java/gunhee/simplememo/service/CategoryService.java
> +@Transactional(readOnly = true)
나쁘진 않은데 ReadOnly 만 사용할 경우 ReadCategoryService 라던지 역할을 빼주면 좋을듯한데
개발자의 선호도에 따라서 달라질 듯
나의 같은 경우 헷갈릴 것 같아!

2024-09-01 04:43 UTC, liquidjoo commented on simplememo/simplememo/src/test/java/gunhee/simplememo/service/CategoryServiceTest.java
> +        assertThat(category.getType()).isEqualTo(result.getType());
assertAll 을 활용해봐
assertAll, assertThat 의 여러개를 사용한 경우 어떤 차이가 있는지도 알아보면 좋을 듯

2024-09-01 04:43 UTC, liquidjoo commented on simplememo/simplememo/src/test/java/gunhee/simplememo/service/MemoServiceTest.java
> +    private MemoRepository memoRepository;
Service 에 로직이 몰려있어서 그런지 단위테스트가 없네
Service 에 로직이 몰려 있게 되면 어떤 상황이 발생할 수 있을까?

2024-09-01 04:43 UTC, liquidjoo commented on simplememo/simplememo/src/test/java/gunhee/simplememo/service/MemoServiceTest.java
> +    private MemoRepository memoRepository;
로직이 거의 없지만서도 만들어진 객체들에 대해서 단위 테스트를 진행해보면 좋을듯

2024-09-02 15:39 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/repository/MemoRepository.java
> +    @Query("select m from Memo m where YEAR(m.memoDate) = :year AND MONTH(m.memoDate) = :month ORDER BY DAY(m.memoDate) DESC")
쿼리 어노테이션을 사용한 이유는 만약 문법 오류가 있을경우 컴파일 타임에 검증을 해줘서 사용했습니다.
그리고 YEAR나 MONTH같은 날짜 함수를 사용하기 위해서 사용했습니다.

2024-09-02 16:22 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/service/CategoryService.java
> +@Transactional(readOnly = true)
현재 해당 클래스의 이름이 CategoryService이고
클래스에 readOnly가 붙어있기때문에 헷갈릴 수 있겠네요!

수정 불가능, 가능한 Service클래스를 분리해놓겠습니다

2024-09-03 04:39 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/dto/memo/StaticsMemoDto.java
> +    private final BigDecimal price;
넵! 수정해놓겠습니다

2024-09-03 12:08 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/domain/memo/Memo.java
> +    @Id @GeneratedValue
GeneratedValue는 DB에따라 설정이 나뉘게 됩니다.

- IDENTITY 설정은 기본 키 생성을 데이터베이스에 위임하는 전략이며 
    MySQL, PostgreSQL, SQL Server, DB2에서 사용됩니다.
    이 전략은 DB에 값을 저장하고 나서야 기본 키 값을 구할 수 있으므로
    em.persist() 사용시 INSERT SQL을 날려서 기본 키 값을 구하고 1차 캐시에 등록가능합니다.
    커밋, 플러시 전에 INSERT SQL을 사용하기때문에 쓰기지연이 동작하지 않습니다.

- SEQUENCE 전략은 데이터베이스 시퀀스 객체를 사용해 기본 키를 생성합니다.
   오라클, PostgreSQL, DB2, H2 데이터베이스에서 사용할 수 있습니다.
   IDENTITY 전략과는 비슷하지만 시퀀스 객체에서 기본 키 값을 받아와서 em.persist()로 1차 캐시에 저장하므로
   트랜잭션을 커밋해서 플러시가 일어나면 엔티티를 DB에 저장합니다.

- TABLE 전략은 키 생성 전용 테이블을 하나 만들고
   이름과 값으로 사용할 컬럼을 만들어 시퀀스를 흉내내는 전략입니다.
   이 전략은 테이블을 사용하므로 모든 데이터베이스에 적용할 수 있습니다.

- UUID 전략은 특정 String값이나 UUID 값을 이용해 기본키를 설정합니다.

- AUTO 전략은 현재 데이터베이스 방언에 따라서 IDENTITY, SEQUENCE, TABLE 전략 중 하나를 자동으로 선택합니다.
   장점은 데이터베이스를 변경해도 코드를 수정할 필요가 없다는 것입니다.
   확정되지 않은 개발 초기나 프로토타입 개발시 편하게 사용할 수 있습니다.

https://docs.jboss.org/hibernate/orm/6.6/introduction/html_single/Hibernate_Introduction.html
공식 홈페이지 조사시 AUTO는 데이터베이스 방언 따라서 전략이 선택된다고 확인했습니다

2024-09-03 13:15 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/dto/memo/MemosResponse.java
> +    }
해당 객체는 DTO가 맞으며 memosVO를 만들어 해당 로직을 분리했습니다.

해당 분리를 해보니 DTO가 간결해졌고
해당 DTO에서 계산되는 값들을 VO에서 해주기 때문에 계산되는 값은 DTO에 의존적이지 않게되었습니다

2024-09-03 13:59 UTC, hegunhee commented on simplememo/simplememo/src/test/java/gunhee/simplememo/service/CategoryServiceTest.java
> +        assertThat(category.getType()).isEqualTo(result.getType());
assertThat의 경우 순서대로 검증할때 에러가 발생되면 그 뒤의 검증은 진행하지않고 종료하지만
assertAll의 경우 모든 검증을 진행 후 에러 사항들을 모두 보여줍니다.

만약 하나의 테스트케이스에 여러개의 assert가 필요할경우 assertAll을 사용하는게 좋습니다.

**추가적으로 알게된 것**
- Junit : 자바에 구축된 자동화 테스트가 가능한 프레임워크
- AssertJ : 자바 테스트에서 유창하고 풍부한 assertions를 작성하는데 사용되는 오픈소스 라이브러리

AssertJ의 경우 보다 풍부한 표현이 가능합니다.

2024-09-03 13:59 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/dto/TotalSum.java
> +    private final BigDecimal totalSum;
넵 감사합니다!

2024-09-03 13:59 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/controller/CategoryController.java
> +    }
넵 작성하였습니다!

2024-09-04 04:49 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/repository/MemoRepository.java
> +            "GROUP BY m.attribute")
JPQL로 사용하다보면 파라미터들을 직접 등록을 해줘야하지만
쿼리 어노테이션을 사용하면 파라미터에 @Param을 등록해주면 자동으로 JPQL에 대입이 됩니다

Query 어노테이션의 경우 현재 JPQL을 사용할 수 있으며 필요에 따라 nativeSql을 사용할 수 있고
페이징 설정도 가능합니다.

혹시 몰라서 Repository를 만들어 entityManager로 동일한 작업을 하는 코드를 만들어봤지만
위에서 말씀드린 파라미터 연동 외에는 별다른 차이를 모르겠습니다

2024-09-04 04:55 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/domain/memo/Memo.java
> +    }
모든 프로퍼티의 경우 같이 묶이는 경우가 없어서
프로퍼티마다 수정할 수 있게 updateXXX 메서드를 추가했습니다.

setXXX로 사용할까도 고민했지만 세터로 오인해 무분별하게 사용할 수 있기때문에
메서드 명을 updateXXX로 결정했습니다.

2024-09-04 06:19 UTC, hegunhee commented on simplememo/simplememo/src/test/java/gunhee/simplememo/service/MemoServiceTest.java
> +    private MemoRepository memoRepository;
Service에 로직이 몰려있게될경우 유지보수가 어렵고 가독성이 떨어지게 되고 테스트가 어려워집니다

Service의 경우 읽기전용과 아닌경우를 분리하였고 그에따른 테스트 코드 클래스를 분리하겠습니다

그리고 찾기의 경우 DTO로 변환하는 과정까지 테스트하겠습니다

2024-09-04 06:29 UTC, hegunhee commented
해당 코드를 작업하면서 계속 고민하던게 Entity -> DTO를 변환하는 곳을 Controller로 할지 Service에서 변환할지 였습니다.

고민 결과 Service에서 변환하는게 적합하다고 생각했습니다.
- Controller단은 클라이언트 요청과 응답에만 집중하는 역할
- OSIV를 off함으로 인해 트랜잭션을 보다 빠르게 사용 가능
- Controller단에 Entity를 노출하지 않아도 됨
과 같은 장점 덕분에 Service에서 변경하도록 하겠습니다.

이것은 1차 피드백 이후 2차 피드백 과정과 같이 작업하겠습니다!

2024-09-04 12:11 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/domain/memo/Memo.java
> +    @Id @GeneratedValue
![image](https://github.com/user-attachments/assets/4d0d8485-4a0e-4349-96ab-c9893deb0ba3)
SEQUENCE 전략의 경우 건너뛰는 key값의 기본값이 50으로 지정되어있는데
해당 결과를 보면 id값이 한번에 50을 뛰어 넘는걸 확인했습니다.

2024-09-09 03:06 UTC, liquidjoo requested changes
확인 후 다시 ~ 알려줘

2024-09-09 03:06 UTC, liquidjoo commented on simplememo/simplememo/src/main/java/gunhee/simplememo/controller/MemoController.java
> +    private final ReadMemoService readMemoService;
이름을 Read로 했으면 MemoService 도 이름을 명확히 해줘야 할 것 같아!

2024-09-09 03:06 UTC, liquidjoo commented on simplememo/simplememo/src/main/java/gunhee/simplememo/controller/MemoController.java
> +        MemosResponse memosResponse = memosVO.toMemosResponses();
vo 넘겨도 되지 않을까?
VO, DTO 차이점 알고 있으면 좋을듯

2024-09-09 03:06 UTC, liquidjoo commented on simplememo/simplememo/src/main/java/gunhee/simplememo/controller/MemoController.java
> +        MemosResponse memoResponses = memosVO.toMemosResponses();
Vo 에서 Response 까지 담당하는것 보다 Response 에서 Vo 및 다른 값을 받아서 처리하면 어떨까?
> 나의 생각이고 개발자마다 생각이 다를 수 있어서 너는 어떤면에서 이렇게 작성했는지 궁금해 알려줘

2024-09-09 03:06 UTC, liquidjoo commented on simplememo/simplememo/src/main/java/gunhee/simplememo/domain/memo/MemosVO.java
> +    }
TotalSum 이라는 객체를 활용하고 있는데 여기는 BigDecimal 로 반환하는 이유는?

2024-09-09 03:06 UTC, liquidjoo commented on simplememo/simplememo/src/main/java/gunhee/simplememo/service/category/ReadCategoryService.java
> +            throw new NoSuchElementException(categoryName+" 카테고리가 존재하지 않습니다.");
NoSuchElement 예외 처리가 맞을까?
> 이건 내가 궁금해서 남겨!! 리스트를 반환하는 것이 아닌데 뭔가 어색해서

2024-09-09 03:06 UTC, liquidjoo commented on simplememo/simplememo/src/test/java/gunhee/simplememo/service/ReadCategoryServiceTest.java
> +        assertThat(resultNotExist).isFalse();
이건 왜 두 번씩 검사를해?

2024-09-13 12:48 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/service/category/ReadCategoryService.java
> +            throw new NoSuchElementException(categoryName+" 카테고리가 존재하지 않습니다.");
먼저 orElseThrow 구문을 사용하게된 이유는
findById의 Exception의 경우 message가 영어값이거나 없기때문에 직관적이지 않다고 판단해서
새로운 Exception을 던지게 되었습니다

처음 CrudRepository(Spring data jpa) findById의 Exception이 NoSuchElementException인줄알고
NoSuchElementException으로 처리하였습니다.

다시 확인해보니 findById의 경우 id값이 없을 때 IllegalArgumentException을 던지는걸 확인했습니다.
원래의 목적대로 동일한 Exception을 던져주되 message값을 변경하기 위함이었기때문에
IlleaglArgumentException으로 던지겠습니다.

2024-09-13 12:51 UTC, hegunhee commented on simplememo/simplememo/src/test/java/gunhee/simplememo/service/ReadCategoryServiceTest.java
> +        assertThat(resultNotExist).isFalse();
뒤의 assertThat의 경우 삭제하지 않은 테스트문입니다... 삭제하겠습니다

2024-09-13 13:13 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/controller/MemoController.java
> +        MemosResponse memosResponse = memosVO.toMemosResponses();
VO는 로직을 가질 수 있고 DTO는 로직을 가지면 안되서 분리한것인데
이렇게하면 Controller에 불필요한 코드가 남는 결과를 만들어낼 수 있겠네요
아래 피드백주신것과 묶어서 VO를 DTO에 넘는 방식으로 변경하겠습니다

처음 DTO에 VO를 넘길까도 고민해봤지만 VO를 DTO에 넘기게 된다면
DTO가 VO에 종속성을 가지기때문에 생성자에 넘기는것이 불필요하다고 생각했습니다.
하지만 해당 VO의 경우 특정 DTO에 필요한 파라미터를 만들어주는 존재이기 때문에
DTO가 해당 VO를 생성자로 받아서 발생하는 문제는 없을것같습니다

2024-09-13 13:32 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/service/category/ReadCategoryService.java
> +            throw new NoSuchElementException(categoryName+" 카테고리가 존재하지 않습니다.");
요약하자면 CrudRepository의 findById메서드에서 던져주는 Exception이 NoSuchElementException인줄알고
메세지만 추가해 똑같은 NoSuchElementException을 던져주려 했습니다.
다시 확인해보니 IllegalArgumentException을 던져줘 IllegalArgumentException을 반환했습니다.

2024-09-13 13:39 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/domain/memo/MemosVO.java
> +    }
위의 TotalSum 객체를 활용하는 메서드와
현재 calculateAttributeSum 메서드는 모두 다른 DTO를 위해 사용됩니다.

하지만 MemosVO에 두 메서드를 둔다면 혼동이 올 수 있기때문에
VO를 두개로 분리해서 각자의 목적에 맞게 사용하겠습니다.

그러는 편이 DTO의 생성자에 VO를 넣었을 때  잘못 사용될 가능성을 줄일 수 있기 때문에
분리하겠습니

2024-09-13 13:51 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/controller/MemoController.java
> +    private final ReadMemoService readMemoService;
넵 알아보기 쉽게 변경하겠습니다!

2024-09-13 13:58 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/controller/MemoController.java
> +    private final ReadMemoService readMemoService;
ReadMemoService, WriteMemoService로 분리하려했지만
엔티티에 집중해서
MemoReadService, MemoWriteService로 변경하겠습니다!

2024-09-14 00:58 UTC, hegunhee commented on simplememo/simplememo/src/main/java/gunhee/simplememo/controller/MemoController.java
> +        MemosResponse memoResponses = memosVO.toMemosResponses();
처음 VO를 도입하기로 하고 DTO의 생성이 VO에 의존한다면
나중에 DTO의 명세가 변경될 경우 문제가 발생될 수 있다고 생각했습니다.
하지만 VO의 경우 DTO로 변경해주는 역할을 하고있기 때문에 
DTO의 명세와는 연관이 없겠네요

위의 코드처럼 작업한다면 VO의 역할이 Controller로 분산되는 것이니
DTO의 생성자에 VO를 추가하여 생성자 안에서 작업하도록 변경하겠습니다
감사합니다!

2024-09-22 13:02 UTC, hegunhee commented
안녕하세요 저스틴
지난번에 코멘트 주신 내용들 보완해서 수정했습니다.

- NoSuchElementException은 JpaRepository에서 해당 Exception을 처리하는 줄 알고있었고
IllegalArgumentException으로 사용하는것을 확인해서 IllegalArgumentException으로 변경했습니다.

- Service 객체의 경우 Read, Write로 직관성 있게 클래스명을 변경했습니다.

- Service 객체 안에서 VO를 변경하는 것이 아닌 VO에서 해당 일을 처리하도록 변경했습니다.

- 동일한 테스트케이스가 두번 검증되는것은 지난번에 사용했던 테스트케이스를 삭제하지않아서 발생한 이슈였습니다!

매번 감사합니다!

2024-09-23 01:59 UTC, liquidjoo approved these changes
고생했어!!! :)

2024-09-23 02:54 UTC, hegunhee commented
감사합니다!!

2024-09-23 02:54 UTC, merged